# Generated by Django 6.0.4 on 2026-04-23 22:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=50, null=True)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], default='planted', max_length=50)),
                ('field_status', models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('completed', 'Completed')], default='active', max_length=50)),
                ('review', models.TextField(blank=True, null=True)),
                ('review_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_fields', models.ManyToManyField(blank=True, related_name='assigned_agents', to='field.fieldmanagement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
