# Generated by Django 6.0.4 on 2026-04-24 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='assigned_fields',
        ),
        migrations.AddField(
            model_name='fieldmanagement',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='field.agents'),
        ),
        migrations.AddField(
            model_name='fieldmanagement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fields', to=settings.AUTH_USER_MODEL),
        ),
    ]
